global:
  scrape_interval: 15s
  external_labels:
    cluster: "thermopus"
    replica: "a"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["prometheus:9090"]

  - job_name: python-worker
    static_configs:
      - targets: ["python-worker:9101"]
    scrape_interval: 5s 